os: linux
dist: bionic

language: ruby
rvm: 2.6.5

before_install:
  - bundle config path 'vendor/bundle'

install:
  - bundle install --quiet

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL error (for htmlproofer)

script:
  - >-
    git clone https://${GH_PAT}@github.com/${GH_USER}/${BUILDER_REPO}.git
    ${HOME}/${BUILDER_REPO} --depth=1 -q
  - cp -r ${HOME}/${BUILDER_REPO}/framework/* .
  - bash _cibuild.sh

branches:
  only: stable

git:
  depth: false # for posts lastmod

cache:
  directories:
    - $TRAVIS_BUILD_DIR/vendor/bundle

notifications:
  email:
    recipients:
      - secure: "fFLqX7uOzFA8RE2AUFlU1mmxMw+rdV6DnODJ/1Gl+3ecNtrv5LeH3c5a4a5ShQqYTrx9BPfD40VRN7UB+lzOdXiWLI9yDGRPPxGG26/WfrKpdQPZilc8zAOEeDnLAJeGZLsUvgmNb3KCXW6S8NPqqh34CfWcTIzjCARhRgO33wcs8X5wP5cugtNqO5Ew/pUcfWcmiuXNX0GNT6l+nL5A7yN+IO5mRHqSRmlfYd5EHhGMTIL4La+Cd1CNv1m4Dl0Ah2cDeJwi5wLnVbqAgunLhAYmDtxIOCVYMTBrP37UiNe/7QeFelyJfODsmMg1mx3WCykbXydC753WVoAlTg6nNoeeI9fmK+/tuLK+sx/KnYfTVGBXQYq39DyV/2o/IfCzEAKImlzFKGD8R13+ddu4B5UML+cby5KBvhTKIGaC5tKoe39z/31UPpy11/EHMCof2BUOzIgu5Hsv4OSNJlw3oRE31oOPn8xP4e7uWR8bRUhAgzN0Cn0ht+UfpemfGAXrp0M3IXQdc9L4azEFqxRhivMTLK/P6INay7IM+DJ30Ht2dWylGw/sxcRTqyNm3YomJQnXIO4xeqTSLulWr80FFHTys3JEDJYrcKvJmpwLFEAOZtwKsZ6ZShrOIA4LE5fgQtakH3ZLJG9a7jVSlMcNIfaSKgjdDQOe6CoRQL7KouA="
    on_success: never

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer