# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage â€º http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: ko # ì–¸ì–´ë¥¼ í•œêµ­ì–´ë¡œ ì„¤ì •

# Change to your timezone â€º https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Seoul # ì„œìš¸ í‘œì¤€ì‹œë¡œ ì„¤ì •

# jekyll-seo-tag settings â€º https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# â†“ --------------------------

title: sumin lee # ë¸”ë¡œê·¸ ì œëª© ì„¤ì •
tagline: archive # ë¶€ê°€ ì„¤ëª… ì„¤ì •

description: >- # SEOë¥¼ ìœ„í•œ ì„¤ëª… (í‚¤ì›Œë“œ)
  Data Analytics, Automation, Sabermetrics

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://ltnalsxl.github.io" # GitHub Pages URL

navigation:
  - text: "Home"
    url: "/"
  - text: "Categories"
    url: "/categories/"
    sublinks:
      - title: "ğŸ“ˆ Data"
        url: "/categories/data/"
      - title: "ğŸ”§ Productivity Tools"
        url: "/categories/productivity-tools/"
      - title: "âš¾ Sports"
        url: "/categories/sports/"
  - text: "Tags"
    url: "/tags/"
  - text: "Archives"
    url: "/archives/"
  - text: "About"
    url: "/about/"



github:
  username: ltnalsxl # GitHub ì‚¬ìš©ìëª…

twitter:
  username: # íŠ¸ìœ„í„° ê³„ì •ì´ ì—†ë‹¤ë©´ ë¹„ì›Œë‘¡ë‹ˆë‹¤

social:
  name: Sumin Lee
  email: fltnadls1011@gmail.com
  links:
    - https://github.com/ltnalsxl # GitHub ë§í¬
    - https://www.linkedin.com/in/your-linkedin-id # LinkedIn ë§í¬
    # í•„ìš” ì‹œ ë‹¤ë¥¸ ì†Œì…œ ë¯¸ë””ì–´ ë§í¬ ì¶”ê°€ ê°€ëŠ¥

    # í•„ìš” ì‹œ ë‹¤ë¥¸ ì†Œì…œ ë¯¸ë””ì–´ ë§í¬ ì¶”ê°€ ê°€ëŠ¥

# Site Verification Settings
webmaster_verifications:
  google: # êµ¬ê¸€ ì¸ì¦ ì½”ë“œ
  bing: # ë¹™ ì¸ì¦ ì½”ë“œ
  alexa: # ì•Œë ‰ì‚¬ ì¸ì¦ ì½”ë“œ
  yandex: # ì–€ë±ìŠ¤ ì¸ì¦ ì½”ë“œ
  baidu: # ë°”ì´ë‘ ì¸ì¦ ì½”ë“œ
  facebook: # í˜ì´ìŠ¤ë¶ ì¸ì¦ ì½”ë“œ

# â†‘ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # Google Analytics ID
  goatcounter:
    id: # GoatCounter ID
  umami:
    id: # Umami ID
    domain: # Umami ë„ë©”ì¸
  matomo:
    id: # Matomo ID
    domain: # Matomo ë„ë©”ì¸
  cloudflare:
    id: # Cloudflare Web Analytics í† í°
  fathom:
    id: # Fathom Site ID

# Page views settings
pageviews:
  provider: # í˜„ì¬ëŠ” 'goatcounter'ë§Œ ì§€ì›

# í…Œë§ˆ ëª¨ë“œ ì„¤ì •
theme_mode: light # light ë˜ëŠ” dark ëª¨ë“œ ì„¤ì • ê°€ëŠ¥

# CDN ì„¤ì •
cdn: "https://chirpy-img.netlify.app"

# ì•„ë°”íƒ€ ì´ë¯¸ì§€ ì„¤ì •
avatar: "/assets/img/avatar.jpg" # ê¹ƒí—™ í”„ë¡œí•„ ì´ë¯¸ì§€ ì—…ë¡œë“œ ê²½ë¡œ (ë¡œì»¬ íŒŒì¼ì„ ì‚¬ìš©í•˜ê±°ë‚˜ URLë¡œ ì„¤ì • ê°€ëŠ¥)

# SEOë¥¼ ìœ„í•œ ì†Œì…œ ë¯¸ë¦¬ë³´ê¸° ì´ë¯¸ì§€ ì„¤ì •
social_preview_image: # SEO `og:image` ë©”íƒ€ íƒœê·¸ìš© ì‚¬ì´íŠ¸ ì „ì—­ ì´ë¯¸ì§€ URL

# í¬ìŠ¤íŠ¸ì˜ ëª©ì°¨ í‘œì‹œ ì„¤ì •
toc: true # ê¸€ì˜ ìš°ì¸¡ì— ëª©ì°¨ í‘œì‹œ

# ëŒ“ê¸€ ì‹œìŠ¤í…œ ì„¤ì • (ì‚¬ìš©í•˜ì§€ ì•Šì„ ê²½ìš° ë¹„ì›Œë‘¡ë‹ˆë‹¤)
comments:
  provider: # [disqus | utterances | giscus]
  disqus:
    shortname: # Disqus shortname ì…ë ¥
  utterances:
    repo: # <gh-username>/<repo> ì„¤ì •
  giscus:
    repo: # <gh-username>/<repo> ì„¤ì •
    repo_id: 
    category: 
    category_id:
    mapping: # ê¸°ë³¸ê°’ì€ 'pathname'
    lang: ko # ì–¸ì–´ ì„¤ì • (ê¸°ë³¸ê°’: ì‚¬ì´íŠ¸ lang ê°’)

# Self-hosted static assets, optional â€º https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, self-host ì‚¬ìš© ì—¬ë¶€ ì„¤ì •
    env: # í™˜ê²½ ì„¤ì • (development | production)

# PWA ì„¤ì • (Progressive Web App)
pwa:
  enabled: true # PWA ê¸°ëŠ¥ ì‚¬ìš©
  cache:
    enabled: true # PWA ì˜¤í”„ë¼ì¸ ìºì‹œ ì‚¬ìš©

paginate: 10 # í•œ í˜ì´ì§€ì— í‘œì‹œí•  í¬ìŠ¤íŠ¸ ìˆ˜

# The base URL of your site
baseurl: "" # ê¸°ë³¸ URL ì„¤ì •

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
