# Sayt konfiguratsiyasi

# Mavzuni import qilish
theme: jekyll-theme-chirpy

# Veb-sahifa tili › http://www.lingoes.net/en/translator/langcode.htm
# Agar `_data/locales` papkasidagi fayllardan biri bilan bir xil nomga ega bo'lsa, layout tili ham o'zgaradi,
# aks holda, layout tili 'en' bo'yicha standart qiymatni ishlatadi.
lang: uz-UZ

# Vaqt zonasini o'zgartirish › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Tashkent

# jekyll-seo-tag sozlamalari › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: "Mr Kakharov" # O'zingizning saytingiz nomini kiriting

tagline: "Web sahifamga xush kelibsiz!" # Saytingiz uchun qisqa tavsif

description: >- # Sayt haqida umumiy ta’rif
  O'zim haqimdagi blog va boshqa foydali ma'lumotlar.

# Saytingiz uchun protokol va xost nomini to'ldiring.
# Masalan, 'https://username.github.io', e'tibor bering, u '/' bilan tugamaydi.
url: "https://mrkakharov.github.io" # GitHub Pages uchun sayt manzili

github:
  username: MrKakharov # Foydalanuvchi nomiga o'zgartirish

twitter:
  username: MrKakharov # Twitter (X) foydalanuvchi nomiga o'zgartirish

social:
  # To'liq ismingizni o'zgartiring.
  # Bu postlarning standart muallifi va Footer'dagi mualliflik huquqi egasi sifatida ko'rsatiladi
  name: Jakhongir Kakharov
  email: devjk@tuta.io # Email manzilingizga o'zgartirish
  links:
    # Birinchi element mualliflik huquqi egasining havolasi sifatida xizmat qiladi
    - https://twitter.com/MrKakharov # Twitter sahifangizga o'zgartirish
    - https://github.com/MrKakharov # GitHub sahifangizga o'zgartirish
    # Qo'shimcha ijtimoiy havolalarni qo'shish uchun quyidagilarni izohdan chiqarib oling
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Sayt tasdiqlash sozlamalari
webmaster_verifications:
  google: # Google tasdiqlash kodini to'ldiring
  bing: # Bing tasdiqlash kodini to'ldiring
  alexa: # Alexa tasdiqlash kodini to'ldiring
  yandex: # Yandex tasdiqlash kodini to'ldiring
  baidu: # Baidu tasdiqlash kodini to'ldiring
  facebook: # Facebook tasdiqlash kodini to'ldiring

# ↑ --------------------------
# `jekyll-seo-tag` sozlamalarining oxiri

# Veb-analitika sozlamalari
analytics:
  google:
    id: # Google Analytics ID ni to'ldiring
  goatcounter:
    id: # GoatCounter ID ni to'ldiring
  umami:
    id: # Umami ID ni to'ldiring
    domain: # Umami domenini to'ldiring
  matomo:
    id: # Matomo ID ni to'ldiring
    domain: # Matomo domenini to'ldiring
  cloudflare:
    id: # Cloudflare Web Analytics tokenini to'ldiring
  fathom:
    id: # Fathom Site ID ni to'ldiring

# Sahifa ko'rish sozlamalari
pageviews:
  provider: # hozirda faqat 'goatcounter' ni qo'llab-quvvatlaydi

# Rang sxemasi sozlamalari.
#
# Eslatma: Bo'sh qoldirilsa, tizimning rang sxemasiga mos keladi,
# va pastki chap burchakda mavzuni qorong'i va yorug' o'rtasida almashtirish uchun tugma bo'ladi.
#
# Mavjud variantlar:
#
#     light — Yorug' rang sxemasidan foydalaning
#     dark — Qorong'i rang sxemasidan foydalaning
#
theme_mode: # [light | dark]

# Media resurslar uchun CDN endpoint.
# E'tibor bering, bir marta tayinlangandan so'ng, CDN URL
# barcha media resurslar (sayt avatar, postlarning rasmlari, audio va video fayllar) yo'llariga qo'shiladi, '/' bilan boshlanadi
#
# masalan, 'https://cdn.com'
cdn: "https://chirpy-img.netlify.app"

# Yon paneldagi avatar, mahalliy yoki CORS resurslarini qo'llab-quvvatlaydi
avatar: "/assets/img/profile.png"

# SEO `og:image` meta tegida ishlatiladigan sayt bo'ylab ijtimoiy oldindan ko'rish tasviri URL manzili.
# Bu oldindan ko'rish tasviri front matter'dagi maxsus `page.image` bilan almashtirilishi mumkin.
social_preview_image: # string, mahalliy yoki CORS resurslari

# boolean turi, postlarda TOC uchun global kalit.
toc: true

comments:
  # Post-izoh tizimi uchun global kalit. Bo'sh qoldirilsa, o'chirilgan deb hisoblanadi.
  provider: # [disqus | utterances | giscus]
  # Provayder variantlari quyidagicha:
  disqus:
    shortname: # Disqus shortname ni to'ldiring. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances sozlamalari › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus variantlari › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # ixtiyoriy, standart qiymat 'pathname'
    strict: # ixtiyoriy, standart qiymat '0'
    input_position: # ixtiyoriy, standart qiymat 'bottom'
    lang: # ixtiyoriy, `site.lang` qiymatiga mos keladi
    reactions_enabled: # ixtiyoriy, standart qiymat '1'

# O'z-o'zidan joylashtirilgan statik aktivlar, ixtiyoriy › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, bo'sh qoldirilsa 'false' deb hisoblanadi
    # Jekyll muhitini aniqlang, bo'sh qoldirilsa ikkala muhit uchun ham amal qiladi
    # faqat `assets.self_host.enabled` 'true' bo'lsa ishlaydi
    env: # [development | production]

pwa:
  enabled: true # PWA xususiyati (o'rnatiladigan) uchun variant
  cache:
    enabled: true # PWA offline cache uchun variant
    # Bu yerda aniqlangan yo'llar PWA cache'dan chiqariladi.
    # Odatda, bu qiymat bir xil domen nomiga ega bo'lgan boshqa veb-saytning `baseurl` qiymati bo'ladi.
    deny_paths:
      # - "/example"  # `<SITE_URL>/example/*` URL'lari PWA tomonidan cache'lanmaydi

paginate: 10

# Saytingizning asosiy URL manzili
baseurl: ""

# ------------ Quyidagi variantlarni o'zgartirish tavsiya etilmaydi ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge variantlari › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # Bu yerda bo'sh qoldirilgan satr loyihadagi barcha fayllarni anglatadi
      type: posts
    values:
      layout: post
      comments: true # Postlarda izohlarni yoqing.
      toc: true # Postlarda TOC ustunini ko'rsating.
      # Quyidagi parametrni o'zgartirmang, agar siz ushbu loyihadagi barcha boshqa post havolalarining kodini yangilashga ishonchingiz komil bo'lmasa.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # `site.collections` ga qarang
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
