name: Lint JS

on:
  push:
    paths:
      - "_javascript/**/*.js"
      - ".github/workflows/scripts/**/*.js"
      - "*.js"
  pull_request:
    paths:
      - "_javascript/**/*.js"
      - ".github/workflows/scripts/*.js"
      - "*.js"

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm i

      - name: Lint JS
        run: npm run lint:js
